datasource:
  dev:
    driverClass: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/masaiqi_dev?allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
  prod:
    driverClass: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/masaiqi_prod?allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456

